export const BOXERS = [
  {
    id: "el-mariana",
    name: "El Mariana",
    age: 21,
    weight: 90,
    height: 180,
    country: "mx",
  },
  {
    id: "plex",
    name: "Plex",
    age: 24,
    weight: 90,
    height: 185,
    country: "es",
  },
  {
    id: "el-mariana",
    name: "El Mariana",
    age: 21,
    weight: 90,
    height: 180,
    country: "mx",
  },
  {
    id: "plex",
    name: "Plex",
    age: 24,
    weight: 90,
    height: 185,
    country: "es",
  },
  {
    id: "el-mariana",
    name: "El Mariana",
    age: 21,
    weight: 90,
    height: 180,
    country: "mx",
  },
  {
    id: "plex",
    name: "Plex",
    age: 24,
    weight: 90,
    height: 185,
    country: "es",
  },
  {
    id: "el-mariana",
    name: "El Mariana",
    age: 21,
    weight: 90,
    height: 180,
    country: "mx",
  },
  {
    id: "plex",
    name: "Plex",
    age: 24,
    weight: 90,
    height: 185,
    country: "es",
  },
  {
    id: "el-mariana",
    name: "El Mariana",
    age: 21,
    weight: 90,
    height: 180,
    country: "mx",
  },
  {
    id: "plex",
    name: "Plex",
    age: 24,
    weight: 90,
    height: 185,
    country: "es",
  },
  {
    id: "el-mariana",
    name: "El Mariana",
    age: 21,
    weight: 90,
    height: 180,
    country: "mx",
  },
  {
    id: "plex",
    name: "Plex",
    age: 24,
    weight: 90,
    height: 185,
    country: "es",
  },
  {
    id: "el-mariana",
    name: "El Mariana",
    age: 21,
    weight: 90,
    height: 180,
    country: "mx",
  },
  {
    id: "plex",
    name: "Plex",
    age: 24,
    weight: 90,
    height: 185,
    country: "es",
  },
  {
    id: "el-mariana",
    name: "El Mariana",
    age: 21,
    weight: 90,
    height: 180,
    country: "mx",
  },
] as const;
